terraform - remote state
keboola/api-error-control pull request #34
Opened 2022-07-11 18:05 UTC by ErikZigo

2022-07-12 05:56 UTC, joker806 requested changes
Jen fixni ten `profile` pls. Jinak dobry

2022-07-12 05:56 UTC, joker806 commented on provisioning/local/main.tf
> +    profile        = "Keboola-Dev-Platform-Services-AWSAdministratorAccess"
Ten `profile` dej prosim pryc, vyber spravnyho accountu resi `role_arn` niz.

2022-07-12 08:03 UTC, ErikZigo commented on provisioning/local/main.tf
> +    profile        = "Keboola-Dev-Platform-Services-AWSAdministratorAccess"
no jo no

2022-07-12 08:03 UTC, ErikZigo commented
updatnul jsem rovnou ten update script

2022-07-13 11:12 UTC, joker806 approved these changes
OK :ok_hand:

2022-07-13 11:16 UTC, merged